In [ ]:
import geopandas as gp

In [ ]:
# Example of loading a shapefile via geopandas
gp.read_file("./data/la/redlining_la/cartodb-query.shp")

,name,holc_id,holc_grade,geometry
0,None,A1,A,"POLYGON ((-118.45744 34.15201, -118.44784 34.1..."
1,None,A10,A,"POLYGON ((-118.11151 34.18311, -118.10943 34.1..."
2,None,A11,A,"POLYGON ((-118.11300 34.15985, -118.11301 34.1..."
3,None,A12,A,"POLYGON ((-118.17123 34.12776, -118.17084 34.1..."
4,None,A13,A,"MULTIPOLYGON (((-118.17458 34.14194, -118.1735..."
...,...,...,...,...
411,None,D7,D,"POLYGON ((-118.12562 34.16699, -118.12559 34.1..."
412,None,D70,D,"POLYGON ((-118.29093 33.79762, -118.29068 33.7..."
413,None,D71,D,"POLYGON ((-118.26136 33.77123, -118.26199 33.7..."
414,None,D8,D,"POLYGON ((-118.08671 34.15636, -118.08177 34.1..."
415,None,D9,D,"POLYGON ((-118.15394 34.14200, -118.15394 34.1..."

In [ ]:
#to-do: Load LA Data sets

In [ ]:
#to-do: Load Bay Area Data sets

In [ ]:
#to-do: decide on appropriate way to group data (FIPS code, neighborhood, county)

In [ ]:
#to-do: appropriately combine data frames to prep for analysis